apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: forex-conversion
  name: forex-conversion-canary
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: forex-conversion
      role: backend
      env: canary
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forex-conversion
        role: backend
        env: canary
    spec:
      containers:
      - image: purvender/mmv1-forex-conversion-service-kubernetes:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: backend
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
#        env:
#          - name: FOREX_EXCHANGE_URI
#            value: http://forex-exchange #-- we are using config maps
        envFrom:
          - configMapRef:
              name: forex-conversion
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: forex-conversion
  name: forex-conversion
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: forex-conversion
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
items:
- apiVersion: v1
  data:
    FOREX_EXCHANGE_URI: http://forex-exchange
  kind: ConfigMap
  metadata:
    name: forex-conversion
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
