apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: forex-conversion
  name: forex-conversion-production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: forex-conversion
      role: frontend
      env: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: forex-conversion
        role: frontend
        env: production
    spec:
      containers:
      - image: purvender/mmv1-forex-conversion-service-kubernetes:0.0.11-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: frontend
        readinessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8100
            path: /actuator/health/liveness
#        env:
#          - name: FOREX_EXCHANGE_URI
#            value: http://forex-exchange #-- we are using config maps
        envFrom:
          - configMapRef:
              name: forex-conversion
      restartPolicy: Always
